const gestor = require('./gestor')

module.exports = app => {
    app.post('/signup', app.api.user.save)
    app.post('/signin', app.api.auth.signin)
    app.post('/validateToken', app.api.auth.validateToken)

    /**
     * Exibição ou captura de ativos do sistema
     */
    app.route('/asset')
        .all(app.config.passport.authenticate())
        .post(app.api.assets.getAsset)

    /**
     * Rota de validação genérica de documentos
     */
    app.route('/validator/:func/:tk')
        .get(app.api.validator.getByFunction)

    /**
     * Rotas de usuários
     */
    app.route('/request-password-reset').post(app.api.user.requestPasswordReset)
    app.route('/user-sms-unlock').post(app.api.user.smsToken)
    app.route('/password-reset/:token').put(app.api.user.passwordReset)
    app.route('/user-token/:token').get(app.api.user.getByToken)
    app.get('/user-unlock/:id/:token', app.api.user.unlock)
    app.post('/user-resend-unlock', app.api.user.mailyNew)
    app.get('/desk-users', app.api.user.getDeskUser)
    app.route('/users/f-a/:func')
        .all(app.config.passport.authenticate())
        .get(app.api.user.getByFunction)
    app.route('/users')
        .all(app.config.passport.authenticate())
        .post(gestor(app.api.user.save))
        .get(app.api.user.get)
    app.route('/users-cpf/:cpf')
        .all(app.config.passport.authenticate())
        .get(app.api.user.getByCpf)
    app.route('/users/:id')
        .all(app.config.passport.authenticate())
        .put(app.api.user.save)
        .get(app.api.user.getById)
        .delete(gestor(app.api.user.remove))
    app.route('/users/locate-servidor-on-client')
        .all(app.config.passport.authenticate())
        .post(app.api.user.locateServidorOnClient)

    /**
     * Rotas de cadastros de servidores
     */
    // app.route('/cadastrosByKeySearch')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.cadastros.getBykeySearch)
    // app.route('/ct/:id').post(app.api.cadastros.getByToken)
    // app.route('/ct/').post(app.api.cadastros.getBatchByToken)
    // app.route('/cidades/:uf').all(app.config.passport.authenticate()).get(app.api.cadastros.getListaCidades)
    // app.route('/cadastros-cpf').all(app.config.passport.authenticate()).get(app.api.cadastros.getListaMatriculasCpf)
    // app.route('/cadastros')
    //     .all(app.config.passport.authenticate())
    //     .post(app.api.cadastros.save)
    //     .get(app.api.cadastros.get)
    //     .patch(app.api.cadastros.getListaServidores)
    // app.route('/cadastros/:id')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.cadastros.getById)
    // app.route('/cadastros/:cpf/:matricula')
    //     .all(app.config.passport.authenticate())
    //     .put(app.api.cadastros.save)
    //     .get(app.api.cadastros.getByCpfMat)
    //     .delete(app.api.cadastros.remove)
    // app.route('/cadastros-by-field/:field/:filter')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.cadastros.getByField)
    // app.route('/cad-recadastro/:idCadS')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.cadSRecadastro.getCurrent)
    //     .post(app.api.cadSRecadastro.save)
    // app.route('/cad-recadastro/:id')
    //     .all(app.config.passport.authenticate())
    //     .delete(app.api.cadSRecadastro.remove)
    // app.route('/cad-movimentacao/:idCadS')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.cadMovimentacao.getCurrent)
    //     .post(app.api.cadMovimentacao.save)
    // app.route('/cad-movimentacao/:idCadS/:id')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.cadMovimentacao.getById)
    //     .put(app.api.cadMovimentacao.save)
    //     .delete(app.api.cadMovimentacao.remove)
    // app.route('/cad-dependente/:idCadS')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.cadDependente.getCurrent)
    //     .post(app.api.cadDependente.save)
    // app.route('/cad-dependente/:idCadS/:id')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.cadDependente.getById)
    //     .put(app.api.cadDependente.save)
    //     .delete(app.api.cadDependente.remove)
    // app.route('/fin-rubricas')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.fRubricas.get)
    // app.route('/fin-rubricas/:idCadS')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.finRubricas.getCurrent)
    //     .post(app.api.finRubricas.save)
    // app.route('/fin-rubricas/:idCadS/:id')
    //     .all(app.config.passport.authenticate())
    //     .put(app.api.finRubricas.save)
    // app.route('/fin-sfuncional/:idCadS')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.finSFuncional.getCurrent)
    //     .post(app.api.finSFuncional.save)
    // app.route('/fin-sfuncional/:idCadS/:id')
    //     .all(app.config.passport.authenticate())
    //     .put(app.api.finSFuncional.save)

    /**
     * Rotas de cadastros diversos
     */
    // app.route('/cad-bancos')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.cadBancos.get)
    //     .patch(app.api.cadBancos.getListaBancos)
    // app.route('/cad-bancos/:id')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.cadBancos.getById)
    // app.route('/cad-cargos')
    //     .all(app.config.passport.authenticate())
    //     .post(app.api.cadCargos.save)
    //     .get(app.api.cadCargos.get)
    //     .patch(app.api.cadCargos.getListaCargos)
    // app.route('/cad-cargos/:id')
    //     .all(app.config.passport.authenticate())
    //     .put(app.api.cadCargos.save)
    //     .get(app.api.cadCargos.getById)
    //     .delete(app.api.cadCargos.remove)
    // app.route('/cad-centros')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.cadCentros.get)
    //     .patch(app.api.cadCentros.getListaCentros)
    // app.route('/cad-centros/:id')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.cadCentros.getById)
    // app.route('/cad-departamentos')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.cadDepartamentos.get)
    //     .patch(app.api.cadDepartamentos.getListaDepartamentos)
    // app.route('/cad-departamentos/:id')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.cadDepartamentos.getById)
    // app.route('/cad-ltrabalho')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.cadLTrabalho.get)
    //     .patch(app.api.cadLTrabalho.getListaLTrabalho)
    // app.route('/cad-ltrabalho/:id')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.cadLTrabalho.getById)
    // app.route('/cad-pccs')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.cadPccs.get)
    //     .patch(app.api.cadPccs.getListaPccs)
    // app.route('/cad-pccs/:id')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.cadPccs.getById)

    /**
     * Rotas de impressões
     */
    // app.route('/relatorios/f-a/:func')
    //     .all(app.config.passport.authenticate())
    //     .post(app.api.printing.getByFunction)

    /**
     * Rotas do financeiro
     */
    // app.route('/fin-eventos')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.finEventos.get)
    //     .post(app.api.finEventos.save)
    // app.route('/fin-eventos/:id')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.finEventos.getById)
    //     .put(app.api.finEventos.save)
    //     .delete(app.api.finEventos.remove)
    // app.route('/fin-basefixa')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.finBaseFixa.get)
    //     .post(app.api.finBaseFixa.save)
    // app.route('/fin-basefixa/:id')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.finBaseFixa.getById)
    //     .put(app.api.finBaseFixa.save)
    //     .delete(app.api.finBaseFixa.remove)
    // app.route('/fin-basefixaeventos')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.finBaseFixaEventos.get)
    //     .post(app.api.finBaseFixaEventos.save)
    // app.route('/fin-basefixaeventos/:id')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.finBaseFixaEventos.getById)
    //     .put(app.api.finBaseFixaEventos.save)
    //     .delete(app.api.finBaseFixaEventos.remove)
    // app.route('/fin-basefixareferencias')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.finBaseFixaReferencias.get)
    //     .post(app.api.finBaseFixaReferencias.save)
    // app.route('/fin-basefixareferencias/:id')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.finBaseFixaReferencias.getById)
    //     .put(app.api.finBaseFixaReferencias.save)
    //     .delete(app.api.finBaseFixaReferencias.remove)
    // app.route('/fin-eventosbase/:id_fin_eventos')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.finEventosBase.get)
    //     .post(app.api.finEventosBase.save)
    // app.route('/fin-eventosbase/:id_fin_eventos/:id')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.finEventosBase.getById)
    //     .put(app.api.finEventosBase.save)
    //     .delete(app.api.finEventosBase.remove)
    // app.route('/fin-eventosdesconto/:id_fin_eventos')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.finEventosDesconto.get)
    //     .post(app.api.finEventosDesconto.save)
    // app.route('/fin-eventosdesconto/:id_fin_eventos/:id')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.finEventosDesconto.getById)
    //     .put(app.api.finEventosDesconto.save)
    //     .delete(app.api.finEventosDesconto.remove)
    // app.route('/fin-eventospercentual/:id_fin_eventos')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.finEventosPercentual.get)
    //     .post(app.api.finEventosPercentual.save)
    // app.route('/fin-eventospercentual/:id_fin_eventos/:id')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.finEventosPercentual.getById)
    //     .put(app.api.finEventosPercentual.save)
    //     .delete(app.api.finEventosPercentual.remove)
    // app.route('/fin-params')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.finParams.get)
    // app.route('/fin-params/f/:field')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.finParams.getByField)

    /**
     * Rotas de consignações
     */
    app.route('/consignatarios')
        .all(app.config.passport.authenticate())
        .post(app.api.consignatarios.save)
        .get(app.api.consignatarios.get)
    app.route('/consignatarios/:id')
        .all(app.config.passport.authenticate())
        .put(app.api.consignatarios.save)
        .get(app.api.consignatarios.getById)
        .delete(app.api.consignatarios.remove)
    app.route('/consignatarios/f/:func')
        .all(app.config.passport.authenticate())
        .get(app.api.consignatarios.getByFunction)
    app.route('/contratos')
        .all(app.config.passport.authenticate())
        .post(app.api.conContratos.save)
        .get(app.api.conContratos.get)
    app.route('/contratos-serv/:id_cadas')
        .all(app.config.passport.authenticate())
        .get(app.api.conContratos.getByCadas)
    app.route('/contratos/:id')
        .all(app.config.passport.authenticate())
        .put(app.api.conContratos.save)
        .get(app.api.conContratos.getById)
        .delete(app.api.conContratos.remove)
    app.route('/contratos/f/:func')
        .get(app.api.conContratos.getByFunction)
    app.route('/contratos/f-a/:func')
        .all(app.config.passport.authenticate())
        .post(app.api.conContratos.getByFunction)
    app.route('/contratos/f/:func')
        .all(app.config.passport.authenticate())
        .post(app.api.conContratos.getByFunction)
    app.route('/con-parcelas/f-a/:func')
        .all(app.config.passport.authenticate())
        .post(app.api.conContrParcelas.getByFunction)
    app.route('/con-parcelas/:id_con_contratos')
        .all(app.config.passport.authenticate())
        .post(app.api.conContrParcelas.save)
        .get(app.api.conContrParcelas.get)
    app.route('/con-parcelas/:id_con_contratos/:id')
        .all(app.config.passport.authenticate())
        .put(app.api.conContrParcelas.save)
        .get(app.api.conContrParcelas.getById)
        .delete(app.api.conContrParcelas.remove)
    app.route('/con-liquidacoes')
        .all(app.config.passport.authenticate())
        .get(app.api.conLiquidacoes.get)
        .post(app.api.conLiquidacoes.save)
    app.route('/con-liquidacoes/:id')
        .all(app.config.passport.authenticate())
        .get(app.api.conLiquidacoes.getById)
        .put(app.api.conLiquidacoes.save)
    app.route('/con-liquidacoes/f/:func')
        .all(app.config.passport.authenticate())
        .get(app.api.conLiquidacoes.getByFunction)
    app.route('/con-eventos/rubricas-consignatario/:id_consignatario')
        .all(app.config.passport.authenticate())
        .get(app.api.conEventos.getEventosConsignados)

    /**
     * Rotas administrativas
     */
    app.route('/sis-events')
        .all(app.config.passport.authenticate())
        .post(app.api.sisEvents.createEventUpd)
        .get(app.api.sisEvents.get)
    app.route('/sis-events/:field')
        .all(app.config.passport.authenticate())
        .get(app.api.sisEvents.getByField)
    // app.route('/orgao')
    //     .all(app.config.passport.authenticate())
    //     .get(app.api.orgao.get)
    app.route('/params')
        .all(app.config.passport.authenticate())
        .post(app.api.params.get)
    app.route('/params/:id')
        .all(app.config.passport.authenticate())
        .get(app.api.params.getById)
    app.route('/ponte-id').post(app.api.params.getPonteId)
    app.route('/siap-id').post(app.api.params.getSiapId)
    app.route('/esocial-id').post(app.api.params.getESocialId)
    app.route('/esocialjar-id').post(app.api.params.getESocialJarId)
    app.route('/mailer-cli')
        .all(app.config.passport.authenticate())
        .post(app.api.mailerCli.mailyCliSender)
    app.route('/mailer-noncli')
        // .all(app.config.passport.authenticate())
        .post(app.api.mailerCli.mailyCliSender)

    /**
     * Rotas da geração e consultas à folha
     */

    // app.route('/folha/f-a/:func')
    //     .all(app.config.passport.authenticate())
    //     .post(app.api.folha.getByFunction)

    /**
     * Rotas do SIAFIC
     */
    app.route('/siafic-apropriacoes')
        .all(app.config.passport.authenticate())
        .post(app.api.siaficApropriacao.saveByBatch)
    app.route('/siafic-desapropriacoes')
        .all(app.config.passport.authenticate())
        .post(app.api.siaficDesapropriacao.saveByBatch)
    app.route('/siafic-transmissao')
        .all(app.config.passport.authenticate())
        .post(app.api.siaficTransmissoes.sends)


    /**
     * Rotas do MGPonte
     */
    // app.route('/cadastros-batch')
    //     .all(app.config.passport.authenticate())
    //     .post(app.api.cadastros.saveByBatch)
    // app.route('/funcional-batch')
    //     .all(app.config.passport.authenticate())
    //     .post(app.api.finSFuncional.saveByBatch)
    // app.route('/financeiro-batch')
    //     .all(app.config.passport.authenticate())
    //     .post(app.api.finRubricas.saveByBatch)
    // app.route('/fin-eventos-batch')
    //     .all(app.config.passport.authenticate())
    //     .post(app.api.finEventos.saveByBatch)
    // app.route('/fin-eventosbase-batch')
    //     .all(app.config.passport.authenticate())
    //     .post(app.api.finEventosBase.saveByBatch)
    // app.route('/fin-eventosdesconto-batch')
    //     .all(app.config.passport.authenticate())
    //     .post(app.api.finEventosDesconto.saveByBatch)
    // app.route('/fin-eventospercentual-batch')
    //     .all(app.config.passport.authenticate())
    //     .post(app.api.finEventosPercentual.saveByBatch)
    // app.route('/fin-basefixa-batch')
    //     .all(app.config.passport.authenticate())
    //     .post(app.api.finBaseFixa.saveByBatch)
    // app.route('/fin-basefixaeventos-batch')
    //     .all(app.config.passport.authenticate())
    //     .post(app.api.finBaseFixaEventos.saveByBatch)
    // app.route('/fin-basefixareferencias-batch')
    //     .all(app.config.passport.authenticate())
    //     .post(app.api.finBaseFixaReferencias.saveByBatch)
    // app.route('/fin-parametros-batch')
    //     .all(app.config.passport.authenticate())
    //     .post(app.api.finParams.saveByBatch)
    // app.route('/cad-movimentacao-batch')
    //     .all(app.config.passport.authenticate())
    //     .post(app.api.cadMovimentacao.saveByBatch)
    // app.route('/orgao-batch')
    //     .all(app.config.passport.authenticate())
    //     .post(app.api.orgao.saveByBatch)
    // app.route('/cad-cargos-batch')
    //     .all(app.config.passport.authenticate())
    //     .post(app.api.cadCargos.saveByBatch)

    /**
    * Novas Rotas /////////////////////////////////////////////////////
    * 
    */
    app.route('/empresa')
        .all(app.config.passport.authenticate())
        .post(app.api.empresa.save)
        .get(app.api.empresa.get)
    app.route('/empresa/:id')
        .all(app.config.passport.authenticate())
        .put(app.api.empresa.save)
        .get(app.api.empresa.getById)
        .delete(app.api.empresa.remove)

    app.route('/es-params')
        .all(app.config.passport.authenticate())
        .post(app.api.esParams.save)
        .get(app.api.esParams.get)
    app.route('/es-params/:id')
        .all(app.config.passport.authenticate())
        .put(app.api.esParams.save)
        .get(app.api.esParams.getById)
        .delete(app.api.esParams.remove)

    app.route('/es-envios')
        .all(app.config.passport.authenticate())
        .post(app.api.esEnvios.save)
        .get(app.api.esEnvios.get)
    app.route('/es-envios/:id')
        .all(app.config.passport.authenticate())
        .put(app.api.esEnvios.save)
        .get(app.api.esEnvios.getById)
        .delete(app.api.esEnvios.remove)

    app.route('/es-rejeicoes')
        .all(app.config.passport.authenticate())
        .post(app.api.esRejeicoes.save)
        .get(app.api.esRejeicoes.get)
    app.route('/es-rejeicoes/:id')
        .all(app.config.passport.authenticate())
        .put(app.api.esRejeicoes.save)
        .get(app.api.esRejeicoes.getById)
        .delete(app.api.esRejeicoes.remove)

    app.route('/emp-resp')
        .all(app.config.passport.authenticate())
        .post(app.api.empResp.save)
        .get(app.api.empResp.get)
    app.route('/emp-resp/:id')
        .all(app.config.passport.authenticate())
        .put(app.api.empResp.save)
        .get(app.api.empResp.getById)
        .delete(app.api.empResp.remove)

    app.route('/emp-resp-contato')
        .all(app.config.passport.authenticate())
        .post(app.api.empRespContato.save)
        .get(app.api.empRespContato.get)
    app.route('/emp-resp-contato/:id')
        .all(app.config.passport.authenticate())
        .put(app.api.empRespContato.save)
        .get(app.api.empRespContato.getById)
        .delete(app.api.empRespContato.remove)

    app.route('/emp-ua')
        .all(app.config.passport.authenticate())
        .post(app.api.empUA.save)
        .get(app.api.empUA.get)
    app.route('/emp-ua/:id')
        .all(app.config.passport.authenticate())
        .put(app.api.empUA.save)
        .get(app.api.empUA.getById)
        .delete(app.api.empUA.remove)

}