select 0 ID, 10 STATUS, 1 EVENTO, timestamp 'now' CREATED_AT, null UPDATED_AT, 1 ID_EMP, 1 ID_LOCAL_PARAMS_TIPO,
       CPF_RESPONSAVEL NR_INSC, null CRC, NOME_RESPONSAVEL NOME, 112 ID_CIDADE, CEP_RESPONSAVEL CEP,
       BAIRRO_RESPONSAVEL BAIRRO, ENDERECO_RESPONSAVEL LOGRADOURO, 0 NR, null COMPLEMENTO,
       D_NASCIMENTO_RESPONSAVEL D_NASCIMENTO
from ORGAO  
