exports.up = function(knex) {
    return knex.schema.createTable('wwmgca_cliente_ativos.servidores', table => {
        table.engine('InnoDB')
        table.charset('utf8mb4')
        table.collate('utf8mb4_general_ci')
        table.increments('id').primary()
        table.integer('status').notNull().default(10)
        table.integer('evento').notNull()
        table.string('created_at').notNull()
        table.string('updated_at')
        table.integer('id_emp').notNull().unsigned().comment("Órgão")
        table.string('cpf_trab', 14).notNull().comment("CPF")
        table.string('nome', 70).notNull().comment("Nome do Trabalhador")
        table.string('nome_social', 70).comment("Nome Social")
        table.integer('id_param_sexo').notNull().unsigned().comment("Sexo")
        table.integer('id_param_raca_cor').notNull().unsigned().comment("Raça/ Cor")
        table.integer('id_param_est_civ').notNull().unsigned().comment("Estado Civil")
        table.integer('id_param_grau_instr').notNull().unsigned().comment("Grau de Instrução")
        table.specificType('dt_nascto', 'char(10)').comment("Data de Nascimento")
        table.integer('id_param_p_nascto').notNull().unsigned().comment("País de Nascimento")
        table.integer('id_param_p_nacld').notNull().unsigned().comment("País de Nacionalidade")
        table.integer('id_param_tplograd').notNull().unsigned().comment("Tipo de Logradouro")
        table.integer('id_cidade').notNull().unsigned().comment("Cidade")
        table.string('cep', 10).notNull().comment("CEP")
        table.string('nr', 255).notNull().comment("Número")
        table.string('bairro', 255).notNull().comment("Bairro")
        table.string('logradouro', 100).notNull().comment("Logradouro")
        table.string('complemento', 255).comment("Complemento")
        table.boolean('def_fisica').notNull().comment("Deficiência Física")
        table.boolean('def_visual').notNull().comment("Deficiência Vísual")
        table.boolean('def_auditiva').notNull().comment("Deficiência Auditiva")
        table.boolean('def_mental').notNull().comment("Deficiência Mental")
        table.boolean('def_intelectual').notNull().comment("Deficiência Intelectual")
        table.boolean('reab_readap').notNull().comment("Reabilitado/Readaptado")
        table.string('observacao', 255).comment("Observação")
        table.string('telefone', 13).comment("Telefone")
        table.string('email', 60).comment("E-mail")
        table.string('mae', 70).comment("Nome da Mãe")
        table.string('pai', 70).comment("Nome do Pai")
        table.string('naturalidade', 60).comment("Naturalidade")

        table.foreign('id_emp').references('id').inTable('wwmgca_api.empresa').onUpdate('CASCADE').onDelete('NO ACTION')
        table.foreign('id_param_sexo').references('id').inTable('wwmgca_api.params').onUpdate('CASCADE').onDelete('NO ACTION')
        table.foreign('id_param_raca_cor').references('id').inTable('wwmgca_api.params').onUpdate('CASCADE').onDelete('NO ACTION')
        table.foreign('id_param_est_civ').references('id').inTable('wwmgca_api.params').onUpdate('CASCADE').onDelete('NO ACTION')
        table.foreign('id_param_grau_instr').references('id').inTable('wwmgca_api.params').onUpdate('CASCADE').onDelete('NO ACTION')
        table.foreign('id_param_p_nascto').references('id').inTable('wwmgca_api.params').onUpdate('CASCADE').onDelete('NO ACTION')
        table.foreign('id_param_p_nacld').references('id').inTable('wwmgca_api.params').onUpdate('CASCADE').onDelete('NO ACTION')
        table.foreign('id_param_tplograd').references('id').inTable('wwmgca_api.params').onUpdate('CASCADE').onDelete('NO ACTION')
        table.foreign('id_cidade').references('id').inTable('wwmgca_api.cidades').onUpdate('CASCADE').onDelete('NO ACTION')
    })
};

exports.down = function(knex) {
    return knex.schema.dropTable('wwmgca_cliente_ativos.servidores')
};