exports.up = function(knex) {
    return knex.schema.createTable('wwmgca_maribondo_ativos.serv_vinculos', table => {
        table.engine('InnoDB')
        table.charset('utf8mb4')
        table.collate('utf8mb4_general_ci')
        table.increments('id').primary()
        table.integer('status').notNull().default(10)
        table.integer('evento').notNull()
        table.string('created_at').notNull()
        table.string('updated_at')
        table.integer('id_serv').notNull().unsigned().comment("Servidor")
        table.integer('id_vinc_principal').notNull().unsigned().comment("Vinculo Principal")
        table.string('matricula', 30).notNull().comment("Matrícula do Trabalhador")
        table.string('sit_func', 30).notNull().comment("1-Ativo; 2-Aposentado; 3-Pensionista")
        table.boolean('tp_reg_prev').notNull().comment("Tipo Regime Previdenciário")
        table.integer('id_param_tp_prov').notNull().unsigned().comment("Vínculo Trabalhista")
        table.specificType('data_exercicio', 'char(10)').notNull().comment("Data da Entrada em Exercício")
        table.boolean('tp_plan_rp').comment("Plano Segregação da Massa")
        table.boolean('teto_rgps').comment("S-Sim, N-Não")
        table.boolean('abono_perm').comment("S-Sim, N-Não / Abono Permanência")
        table.specificType('d_inicio_abono', 'char(10)').notNull().comment("Data de Início Abono")
        table.specificType('d_ing_cargo', 'char(10)').notNull().comment("Data de Ingressão no Cargo")
        table.integer('id_cargo').notNull().unsigned().comment("Cargo")
        table.boolean('acum_cargo').comment("S-Sim, N-Não / Acumulável")
        table.integer('id_param_cod_categ').notNull().unsigned().comment("Código da Categoria")
        table.string('qtd_hr_sem', 4).comment("Quantidade de Horas Semanais")
        table.integer('id_param_tp_jor').notNull().unsigned().comment("Tipo de Jornada")
        table.integer('id_param_tmp_parc').notNull().unsigned().comment("Tempo Parcial")
        table.boolean('hr_noturno').notNull().default("N").comment("S-Sim, N-Não")
        table.string('desc_jornd', 999).comment("Descrição de Jornada")
        table.string('pis').comment("PIS")
        table.specificType('dt_pis', 'char(10)').comment("Data do PIS")
        table.specificType('tempo_servico', 'char(10)').comment("Tempo de Serviço")
        table.specificType('tempo_final', 'char(10)').comment("Tempo Final")
        table.string('titulo').comment("Título")
        table.string('tit_uf').comment("UF do Título")
        table.string('tit_zona').comment("Zona do Título")
        table.string('tit_secao').comment("Seção do Título")
        table.specificType('dt_nomeacao', 'char(10)').comment("Data da Nomeação")
        table.string('nom_edital').comment("Nome do Edital")
        table.string('nom_nr_inscr').comment("Número Inscrição")
        table.integer('id_siap_pub').notNull().unsigned().comment("Publicação")
        table.integer('id_param_grau_exp').notNull().unsigned().comment("Grau de Experiência")

        table.foreign('id_serv').references('id').inTable('servidores').onUpdate('CASCADE').onDelete('NO ACTION')
        table.foreign('id_param_tp_prov').references('id').inTable('wwmgca_api.params').onUpdate('CASCADE').onDelete('NO ACTION')
        table.foreign('id_cargo').references('id').inTable('aux_cargos').onUpdate('CASCADE').onDelete('NO ACTION')
        table.foreign('id_param_cod_categ').references('id').inTable('wwmgca_api.params').onUpdate('CASCADE').onDelete('NO ACTION')
        table.foreign('id_param_tp_jor').references('id').inTable('wwmgca_api.params').onUpdate('CASCADE').onDelete('NO ACTION')
        table.foreign('id_param_tmp_parc').references('id').inTable('wwmgca_api.params').onUpdate('CASCADE').onDelete('NO ACTION')
        table.foreign('id_siap_pub').references('id').inTable('siap_publicacoes').onUpdate('CASCADE').onDelete('NO ACTION')
        table.foreign('id_param_grau_exp').references('id').inTable('wwmgca_api.params').onUpdate('CASCADE').onDelete('NO ACTION')
    })
};

exports.down = function(knex) {
    return knex.schema.dropTable('wwmgca_maribondo_ativos.serv_vinculos')
};