
import { defineComponent, onMounted } from "vue";
import { usePrimeVue } from "primevue/config";

export default defineComponent({
    setup() {
        const changeToPortuguese = () => {
            const primevue = usePrimeVue();
            primevue.config.locale.startsWith = "Começa com"
            primevue.config.locale.contains = "contém"
            primevue.config.locale.notContains = "Não contém"
            primevue.config.locale.endsWith = "Termina com"
            primevue.config.locale.equals = "É igual a"
            primevue.config.locale.notEquals = "Não é igual"
            primevue.config.locale.noFilter = "Sem filtro"
            primevue.config.locale.lt = "Menor que"
            primevue.config.locale.lte = "Menos que ou igual a"
            primevue.config.locale.gt = "Maior que"
            primevue.config.locale.gte = "Melhor que ou igual a"
            primevue.config.locale.dateIs = "Data é"
            primevue.config.locale.dateIsNot = "Data não é"
            primevue.config.locale.dateBefore = "A data é anterior"
            primevue.config.locale.dateAfter = "A data é depois"
            primevue.config.locale.clear = "Limpar"
            primevue.config.locale.apply = "Aplicar"
            primevue.config.locale.matchAll = "Corresponder a todos"
            primevue.config.locale.matchAny = "Corresponder a qualquer"
            primevue.config.locale.addRule = "Adicionar regra"
            primevue.config.locale.removeRule = "Remover regra"
            primevue.config.locale.accept = "Sim"
            primevue.config.locale.reject = "Não"
            primevue.config.locale.choose = "Escolher"
            primevue.config.locale.upload = "Carregar"
            primevue.config.locale.cancel = "Cancelar"
            primevue.config.locale.completed = "Concluído"
            primevue.config.locale.pending = "Pendente"
            primevue.config.locale.dayNames = ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado']
            primevue.config.locale.dayNamesShort = ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb']
            primevue.config.locale.monthNames = ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro']
            primevue.config.locale.monthNamesShort = ['Jan', 'Fev', 'Mar', 'Abr', 'Maio', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez']
            primevue.config.locale.chooseYear = "Escolha o ano"
            primevue.config.locale.chooseMonth = "Escolha o mês"
            primevue.config.locale.chooseDate = "Escolha a data"
            primevue.config.locale.prevDecade = "Década anterior"
            primevue.config.locale.nextDecade = "próxima década"
            primevue.config.locale.prevYear = "Ano anterior"
            primevue.config.locale.nextYear = "Próximo ano"
            primevue.config.locale.prevMonth = "Mês anterior"
            primevue.config.locale.nextMonth = "Próximo mês"
            primevue.config.locale.prevHour = "Hora anterior"
            primevue.config.locale.nextHour = "próxima hora"
            primevue.config.locale.prevMinute = "Minuto anterior"
            primevue.config.locale.nextMinute = "próximo minuto"
            primevue.config.locale.prevSecond = "Segundo anterior"
            primevue.config.locale.nextSecond = "próximo segundo"
            primevue.config.locale.am = "manhã"
            primevue.config.locale.pm = "tarde"
            primevue.config.locale.today = "Hoje"
            primevue.config.locale.weekHeader = "Sem"
            primevue.config.locale.firstDayOfWeek = 0
            primevue.config.locale.dateFormat = "dd/mm/yy"
            primevue.config.locale.weak = "Fraco"
            primevue.config.locale.medium = "Médio"
            primevue.config.locale.strong = "Forte"
            primevue.config.locale.passwordPrompt = "Insira uma senha"
            primevue.config.locale.emptySearchMessage = "Nenhum resultado encontrado"
            primevue.config.locale.searchMessage = "{0} resultados disponíveis"
            primevue.config.locale.selectionMessage = "{0} itens selecionados"
            primevue.config.locale.emptySelectionMessage = "Nenhum item selecionado"
            primevue.config.locale.emptySearchMessage = "Nenhum resultado encontrado"
            primevue.config.locale.emptyMessage = "Nenhuma opção disponível"
            primevue.config.locale.aria.trueLabel = "Verdadeiro"
            primevue.config.locale.aria.falseLabel = "Falso"
            primevue.config.locale.aria.nullLabel = "Não selecionado"
            primevue.config.locale.aria.star = "1 estrela"
            primevue.config.locale.aria.stars = "{star} estrelas"
            primevue.config.locale.aria.selectAll = "Todos os itens selecionados"
            primevue.config.locale.aria.unselectAll = "Todos os itens desmarcados"
            primevue.config.locale.aria.close = "Fechar"
            primevue.config.locale.aria.previous = "Anterior"
            primevue.config.locale.aria.next = "Próximo"
            primevue.config.locale.aria.navigation = "Navegação"
            primevue.config.locale.aria.scrollTop = "Rolar para cima"
            primevue.config.locale.aria.moveTop = "Mover para cima"
            primevue.config.locale.aria.moveUp = "Subir"
            primevue.config.locale.aria.moveDown = "Mover para baixo"
            primevue.config.locale.aria.moveBottom = "Mover para baixo"
            primevue.config.locale.aria.moveToTarget = "Mover para o alvo"
            primevue.config.locale.aria.moveToSource = "Mover para a fonte"
            primevue.config.locale.aria.moveAllToTarget = "Mover tudo para o alvo"
            primevue.config.locale.aria.moveAllToSource = "Mover tudo para a origem"
            primevue.config.locale.aria.pageLabel = "Página {page}"
            primevue.config.locale.aria.firstPageLabel = "Primeira página"
            primevue.config.locale.aria.lastPageLabel = "Última página"
            primevue.config.locale.aria.nextPageLabel = "Próxima página"
            primevue.config.locale.aria.prevPageLabel = "Página anterior"
            primevue.config.locale.aria.rowsPerPageLabel = "Linhas por página"
            primevue.config.locale.aria.jumpToPageDropdownLabel = "Ir para o menu suspenso da página"
            primevue.config.locale.aria.jumpToPageInputLabel = "Ir para entrada de página"
            primevue.config.locale.aria.selectRow = "Linha selecionada"
            primevue.config.locale.aria.unselectRow = "Linha não selecionada"
            primevue.config.locale.aria.expandRow = "Linha expandida"
            primevue.config.locale.aria.collapseRow = "Linha recolhida"
            primevue.config.locale.aria.showFilterMenu = "Mostrar menu de filtro"
            primevue.config.locale.aria.hideFilterMenu = "Ocultar menu de filtro"
            primevue.config.locale.aria.filterOperator = "Operador de filtro"
            primevue.config.locale.aria.filterConstraint = "Restrição de filtro"
            primevue.config.locale.aria.editRow = "Editar linha"
            primevue.config.locale.aria.saveEdit = "Salvar Editar"
            primevue.config.locale.aria.cancelEdit = "Cancelar edição"
            primevue.config.locale.aria.listView = "Exibição de lista"
            primevue.config.locale.aria.gridView = "Exibição em grade"
            primevue.config.locale.aria.slide = "Deslizar"
            primevue.config.locale.aria.slideNumber = "{slideNumber}"
            primevue.config.locale.aria.zoomImage = "Ampliar Imagem"
            primevue.config.locale.aria.zoomIn = "Mais Zoom"
            primevue.config.locale.aria.zoomOut = "Reduzir o zoom"
            primevue.config.locale.aria.rotateRight = "Vire à direita"
            primevue.config.locale.aria.rotateLeft = "Vire à esquerda"
        }

        onMounted(() => {
            changeToPortuguese();
        })
    }
});