INSERT INTO `wwmgca_api`.`params` (`id`, `status`, `evento`, `created_at`, `updated_at`, `dominio`, `meta`, `value`, `label`)
values
(0,10,1,now(),null,'root','mtvDeslig','01','Rescisão com justa causa, por iniciativa do empregador'),
(0,10,1,now(),null,'root','mtvDeslig','02','Rescisão sem justa causa, por iniciativa do empregador'),	
(0,10,1,now(),null,'root','mtvDeslig','03','Rescisão antecipada do contrato a termo por iniciativa do empregador'),
(0,10,1,now(),null,'root','mtvDeslig','04','Rescisão antecipada do contrato a termo por iniciativa do empregado'),
(0,10,1,now(),null,'root','mtvDeslig','05','Rescisão por culpa recíproca'),
(0,10,1,now(),null,'root','mtvDeslig','06','Rescisão por término do contrato a termo'),	
(0,10,1,now(),null,'root','mtvDeslig','07','Rescisão do contrato de trabalho por iniciativa do empregado'),
(0,10,1,now(),null,'root','mtvDeslig','08','Rescisão do contrato de trabalho por interesse do(a) empregado(a), nas hipóteses previstas nos arts. 394 e 483, § 1º, da CLT'),	
(0,10,1,now(),null,'root','mtvDeslig','09','Rescisão por opção do empregado em virtude de falecimento do empregador individual ou empregador doméstico'),	
(0,10,1,now(),null,'root','mtvDeslig','10','Rescisão por falecimento do empregado'),	
(0,10,1,now(),null,'root','mtvDeslig','11','Transf. de empregado para empresa do mesmo grupo empresarial que tenha assumido os encargos trabalhistas, sem que tenha havido rescisão do contrato de trabalho'),	
(0,10,1,now(),null,'root','mtvDeslig','12','Transf. de empregado da empresa consorciada para o consórcio que tenha assumido os encargos trabalhistas, e vice-versa, sem que tenha havido rescisão do contrato de trabalho'),
(0,10,1,now(),null,'root','mtvDeslig','13','Transf. de empregado de empresa ou consórcio, para outra empresa ou consórcio que tenha assumido os encargos trabalhistas por motivo de sucessão (fusão, cisão ou incorporação), sem que tenha havido rescisão do contrato de trabalho'),	
(0,10,1,now(),null,'root','mtvDeslig','14','Rescisão do contrato de trabalho por encerramento da empresa, de seus estabelecimentos ou supressão de parte de suas atividades ou falecimento do empregador individual ou empregador doméstico sem continuação da atividade'),	
(0,10,1,now(),null,'root','mtvDeslig','16','Declaração de nulidade do contrato de trabalho por infringência ao inciso II do art. 37 da Constituição Federal, quando mantido o direito ao salário'),	
(0,10,1,now(),null,'root','mtvDeslig','17','Rescisão indireta do contrato de trabalho'),
(0,10,1,now(),null,'root','mtvDeslig','21','Reforma militar'),
(0,10,1,now(),null,'root','mtvDeslig','22','Reserva militar'),	
(0,10,1,now(),null,'root','mtvDeslig','23','Exoneração'),
(0,10,1,now(),null,'root','mtvDeslig','24','Demissão'),
(0,10,1,now(),null,'root','mtvDeslig','25','Vacância de cargo efetivo'),	
(0,10,1,now(),null,'root','mtvDeslig','26','Rescisão do contrato de trabalho por paralisação temporária ou definitiva da empresa, estabelecimento ou parte das atividades motivada por atos de autoridade municipal, estadual ou federal'),	
(0,10,1,now(),null,'root','mtvDeslig','27','Rescisão por motivo de força maior'),	
(0,10,1,now(),null,'root','mtvDeslig','29','Redistribuição ou Reforma Administrativa'),	
(0,10,1,now(),null,'root','mtvDeslig','30','Mudança de regime trabalhista'),	
(0,10,1,now(),null,'root','mtvDeslig','31','Reversão de reintegração'),	
(0,10,1,now(),null,'root','mtvDeslig','32','Extravio de militar'),
(0,10,1,now(),null,'root','mtvDeslig','33','Rescisão por acordo entre as partes (art. 484-A da CLT)'),	
(0,10,1,now(),null,'root','mtvDeslig','34','Transferência de titularidade do empregado doméstico para outro representante da mesma unidade familiar'),	
(0,10,1,now(),null,'root','mtvDeslig','36','Mudança de CPF'),	
(0,10,1,now(),null,'root','mtvDeslig','37','Remoção, em caso de alteração do órgão declarante'),	
(0,10,1,now(),null,'root','mtvDeslig','38','Aposentadoria, exceto por invalidez'),	
(0,10,1,now(),null,'root','mtvDeslig','39','Aposentadoria de servidor estatutário, por invalidez'),	
(0,10,1,now(),null,'root','mtvDeslig','40','Término do exercício do mandato eletivo'),	
(0,10,1,now(),null,'root','mtvDeslig','41','Rescisão do contrato de aprendizagem por desempenho insuficiente ou inadaptação do aprendiz'),	
(0,10,1,now(),null,'root','mtvDeslig','42','Rescisão do contrato de aprendizagem por ausência injustificada do aprendiz à escola que implique perda do ano letivo'),	
(0,10,1,now(),null,'root','mtvDeslig','43','Transferência de empregado de empresa considerada inapta por inexistência de fato'),	
(0,10,1,now(),null,'root','mtvDeslig','44','Agrupamento contratual')
