INSERT INTO `wwmgca_api`.`params` (`id`, `status`, `evento`, `created_at`, `updated_at`, `dominio`, `meta`, `value`, `label`)
values
(0,10,1,now(),null,'root','classTrib','01','Empresa enquadrada no regime de tributação Simples Nacional com tributação previdenciária substituída'),
(0,10,1,now(),null,'root','classTrib','02','Empresa enquadrada no regime de tributação Simples Nacional com tributação previdenciária não substituída'),
(0,10,1,now(),null,'root','classTrib','03','Empresa enquadrada no regime de tributação Simples Nacional com tributação previdenciária substituída e não substituída'),
(0,10,1,now(),null,'root','classTrib','04','Microempreendedor Individual - MEI'),
(0,10,1,now(),null,'root','classTrib','06','Agroindústria'),
(0,10,1,now(),null,'root','classTrib','07','Produtor rural Pessoa Jurídica'),
(0,10,1,now(),null,'root','classTrib','09','Órgão Gestor de Mão de Obra - OGMO'),
(0,10,1,now(),null,'root','classTrib','10','Entidade sindical a que se refere a Lei 12.023/2009'),
(0,10,1,now(),null,'root','classTrib','11','Associação desportiva que mantém clube de futebol profissional'),
(0,10,1,now(),null,'root','classTrib','13','Banco, caixa econômica, sociedade de crédito, financiamento e investimento e demais empresas relacionadas no parágrafo 1º do art. 22 da Lei 8.212/1991'),
(0,10,1,now(),null,'root','classTrib','14','Sindicatos em geral, exceto aquele classificado no código [10]'),
(0,10,1,now(),null,'root','classTrib','21','Pessoa Física, exceto segurado especial'),
(0,10,1,now(),null,'root','classTrib','22','Segurado especial, inclusive quando for empregador doméstico'),
(0,10,1,now(),null,'root','classTrib','60','Missão diplomática ou repartição consular de carreira estrangeira'),
(0,10,1,now(),null,'root','classTrib','70','Empresa de que trata o Decreto 5.436/2005'),
(0,10,1,now(),null,'root','classTrib','80','Entidade beneficente de assistência social isenta de contribuições sociais'),
(0,10,1,now(),null,'root','classTrib','85','Administração direta da União, Estados, Distrito Federal e Municípios; autarquias e fundações públicas'),
(0,10,1,now(),null,'root','classTrib','99','Pessoas Jurídicas em geral')
