INSERT INTO `wwmgca_api`.`params` (`id`, `status`, `evento`, `created_at`, `updated_at`, `dominio`, `meta`, `value`, `label`)
values
(0,10,1,now(),null,'root','tpBenef','0101','Aposentadoria por idade e tempo de contribuição - Proventos com integralidade, revisão pela paridade'),
(0,10,1,now(),null,'root','tpBenef','0102','Aposentadoria por idade e tempo de contribuição - Proventos pela média, reajuste manter valor real'),
(0,10,1,now(),null,'root','tpBenef','0103','Aposentadoria por idade - Proventos proporcionais calculado sobre integralidade, revisão pela paridade'),
(0,10,1,now(),null,'root','tpBenef','0104','Aposentadoria por idade - Proventos proporcionais calculado sobre a média, reajuste manter valor real'),
(0,10,1,now(),null,'root','tpBenef','0105','Aposentadoria compulsória - Proventos proporcionais calculado sobre integralidade, revisão pela paridade'),
(0,10,1,now(),null,'root','tpBenef','0106','Aposentadoria compulsória - Proventos proporcionais calculado sobre a média, reajuste manter valor real'),
(0,10,1,now(),null,'root','tpBenef','0107','Aposentadoria de professor - Proventos com integralidade, revisão pela paridade'),
(0,10,1,now(),null,'root','tpBenef','0108','Aposentadoria de professor - Proventos pela média, reajuste manter valor real'),
(0,10,1,now(),null,'root','tpBenef','0109','Aposentadoria de servidor vinculado a RPC - Proventos limitados ao teto do RGPS'),
(0,10,1,now(),null,'root','tpBenef','0201','Aposentadoria especial - Risco'),
(0,10,1,now(),null,'root','tpBenef','0202','Aposentadoria especial - Exposição a agentes nocivos'),
(0,10,1,now(),null,'root','tpBenef','0203','Aposentadoria da pessoa com deficiência'),
(0,10,1,now(),null,'root','tpBenef','0204','Aposentadoria especial do policial civil'),
(0,10,1,now(),null,'root','tpBenef','0205','Aposentadoria especial - Risco - Servidor vinculado a RPC - Proventos limitados ao teto do RGPS'),
(0,10,1,now(),null,'root','tpBenef','0206','Aposentadoria especial - Exposição a agentes nocivos - Servidor vinculado a RPC - Proventos limitados ao teto do RGPS'),
(0,10,1,now(),null,'root','tpBenef','0207','Aposentadoria da pessoa com deficiência - Servidor vinculado a RPC - Proventos limitados ao teto do RGPS'),
(0,10,1,now(),null,'root','tpBenef','0208','Aposentadoria especial de policial - Servidor vinculado a RPC - Proventos limitados ao teto do RGPS'),
(0,10,1,now(),null,'root','tpBenef','0301','Aposentadoria por invalidez - Proventos com integralidade, revisão pela paridade'),
(0,10,1,now(),null,'root','tpBenef','0302','Aposentadoria por invalidez - Proventos pela média, reajuste manter valor real'),
(0,10,1,now(),null,'root','tpBenef','0303','Aposentadoria por invalidez - Proventos proporcionais calculado sobre integralidade, revisão pela paridade'),
(0,10,1,now(),null,'root','tpBenef','0304','Aposentadoria por invalidez - Proventos proporcionais calculado sobre a média, reajuste manter valor real'),
(0,10,1,now(),null,'root','tpBenef','0305','Aposentadoria por invalidez - Servidor vinculado a RPC - Proventos limitados ao teto do RGPS'),
(0,10,1,now(),null,'root','tpBenef','0401','Reforma por invalidez'),
(0,10,1,now(),null,'root','tpBenef','0402','Reforma'),
(0,10,1,now(),null,'root','tpBenef','0403','Reforma compulsória proporcional'),
(0,10,1,now(),null,'root','tpBenef','0404','Reforma compulsória integral'),
(0,10,1,now(),null,'root','tpBenef','0405','Reforma por incapacidade definitiva'),
(0,10,1,now(),null,'root','tpBenef','0501','Reserva remunerada compulsória integral'),
(0,10,1,now(),null,'root','tpBenef','0502','Reserva remunerada integral'),
(0,10,1,now(),null,'root','tpBenef','0503','Reserva remunerada proporcional'),
(0,10,1,now(),null,'root','tpBenef','0504','Reserva remunerada compulsória proporcional'),
(0,10,1,now(),null,'root','tpBenef','0601','Pensão por morte (art. 40, § 7º, da CF/1988)'),
(0,10,1,now(),null,'root','tpBenef','0602','Pensão por morte com paridade, decorrente do art. 6º-A da EC 41/2003'),
(0,10,1,now(),null,'root','tpBenef','0603','Pensão por morte com paridade, decorrente do art. 3º da EC 47/2005'),
(0,10,1,now(),null,'root','tpBenef','0604','Pensão por morte militar'),
(0,10,1,now(),null,'root','tpBenef','0701','Complementação de aposentadoria do RGPS'),
(0,10,1,now(),null,'root','tpBenef','0702','Complementação de pensão por morte do RGPS'),
(0,10,1,now(),null,'root','tpBenef','0801','Aposentadoria sem paridade concedida antes da obrigatoriedade de envio dos eventos não periódicos para entes públicos no eSocial'),
(0,10,1,now(),null,'root','tpBenef','0802','Aposentadoria com paridade concedida antes da obrigatoriedade de envio dos eventos não periódicos para entes públicos no eSocial'),
(0,10,1,now(),null,'root','tpBenef','0803','Aposentadoria por invalidez com paridade concedida antes da obrigatoriedade de envio dos eventos não periódicos para entes públicos no eSocial'),
(0,10,1,now(),null,'root','tpBenef','0804','Aposentadoria por invalidez sem paridade concedida antes da obrigatoriedade de envio dos eventos não periódicos para entes públicos no eSocial'),
(0,10,1,now(),null,'root','tpBenef','0805','Transferência para reserva concedida antes da obrigatoriedade de envio dos eventos não periódicos para entes públicos no eSocial'),
(0,10,1,now(),null,'root','tpBenef','0806','Reforma concedida antes da obrigatoriedade de envio dos eventos não periódicos para entes públicos no eSocial'),
(0,10,1,now(),null,'root','tpBenef','0807','Pensão por morte com paridade concedida antes da obrigatoriedade de envio dos eventos não periódicos para entes públicos no eSocial'),
(0,10,1,now(),null,'root','tpBenef','0808','Pensão por morte sem paridade concedida antes da obrigatoriedade de envio dos eventos não periódicos para entes públicos no eSocial'),
(0,10,1,now(),null,'root','tpBenef','0809','Outros benefícios previdenciários concedidos antes da obrigatoriedade de envio dos eventos não periódicos para entes públicos no eSocial'),
(0,10,1,now(),null,'root','tpBenef','0810','Aposentadoria de parlamentar - Plano próprio'),
(0,10,1,now(),null,'root','tpBenef','0811','Aposentadoria de servidor vinculado ao Poder Legislativo - Plano próprio'),
(0,10,1,now(),null,'root','tpBenef','0812','Pensão por morte - Plano próprio'),
(0,10,1,now(),null,'root','tpBenef','0901','Benefício especial proporcional - Servidor pertencente a RPPS que opta pelo RPC da União'),
(0,10,1,now(),null,'root','tpBenef','0902','Benefício especial proporcional - Servidor pertencente a RPPS que opta pelo RPC - Demais entes da Federação, de acordo com as disposições das leis específicas'),
(0,10,1,now(),null,'root','tpBenef','0909','Outros benefícios especiais com vínculo previdenciário'),
(0,10,1,now(),null,'root','tpBenef','1001','Pensão especial sem vínculo previdenciário'),
(0,10,1,now(),null,'root','tpBenef','1009','Outros benefícios sem vínculo previdenciário'),
(0,10,1,now(),null,'root','tpBenef','1101','Aposentadoria voluntária com proventos proporcionais ao tempo de mandato - Leis próprias'),
(0,10,1,now(),null,'root','tpBenef','1102','Aposentadoria voluntária com proventos integrais ao tempo de mandato - Leis próprias'),
(0,10,1,now(),null,'root','tpBenef','1103','Aposentadoria por invalidez permanente - Proventos integrais - Leis próprias'),
(0,10,1,now(),null,'root','tpBenef','1104','Aposentadoria por invalidez permanente - Proventos proporcionais ao tempo de mandato - Leis próprias'),
(0,10,1,now(),null,'root','tpBenef','1105','Pensão por morte de parlamentar - Lei específica'),
(0,10,1,now(),null,'root','tpBenef','1106','Pensão por morte de parlamentar - Planos anteriores à EC 20/1998')