INSERT INTO `wwmgca_api`.`params` (`id`, `status`, `evento`, `created_at`, `updated_at`, `dominio`, `meta`, `value`, `label`)
values
(0,10,1,now(),null,'root','codIncIRRF','0','Rendimento não tributável'),
(0,10,1,now(),null,'root','codIncIRRF','1','Rendimento não tributável em função de acordos internacionais de bitributação'),
(0,10,1,now(),null,'root','codIncIRRF','9','Verba transitada pela folha de pagamento de natureza diversa de rendimento ou retenção/isenção/dedução de IR (exemplo: desconto de convênio farmácia, desconto de consignações, etc.)'),
(0,10,1,now(),null,'root','codIncIRRF','11','Remuneração mensal'),
(0,10,1,now(),null,'root','codIncIRRF','12','13º salário'),
(0,10,1,now(),null,'root','codIncIRRF','13','Férias'),
(0,10,1,now(),null,'root','codIncIRRF','14','PLR'),
(0,10,1,now(),null,'root','codIncIRRF','15','Rendimentos Recebidos Acumuladamente RRA'),
(0,10,1,now(),null,'root','codIncIRRF','31','Remuneração mensal'),
(0,10,1,now(),null,'root','codIncIRRF','32','13º salário'),
(0,10,1,now(),null,'root','codIncIRRF','33','Férias'),
(0,10,1,now(),null,'root','codIncIRRF','34','PLR'),
(0,10,1,now(),null,'root','codIncIRRF','35','Rendimentos Recebidos Acumuladamente RRA'),
(0,10,1,now(),null,'root','codIncIRRF','41','Previdência Social Oficial PSO Remuneração mensal'),
(0,10,1,now(),null,'root','codIncIRRF','42','PSO 13º salário'),
(0,10,1,now(),null,'root','codIncIRRF','43','PSO Férias'),
(0,10,1,now(),null,'root','codIncIRRF','44','PSO RRA'),
(0,10,1,now(),null,'root','codIncIRRF','46','Previdência complementar Salário mensal'),
(0,10,1,now(),null,'root','codIncIRRF','47','Previdência complementar 13º salário'),
(0,10,1,now(),null,'root','codIncIRRF','48','Previdência complementar Férias'),
(0,10,1,now(),null,'root','codIncIRRF','51','Pensão alimentícia Remuneração mensal'),
(0,10,1,now(),null,'root','codIncIRRF','52','Pensão alimentícia 13º salário'),
(0,10,1,now(),null,'root','codIncIRRF','53','Pensão alimentícia Férias'),
(0,10,1,now(),null,'root','codIncIRRF','54','Pensão alimentícia PLR'),
(0,10,1,now(),null,'root','codIncIRRF','55','Pensão alimentícia RRA'),
(0,10,1,now(),null,'root','codIncIRRF','61','Fundo de Aposentadoria Programada Individual FAPI Remuneração mensal'),
(0,10,1,now(),null,'root','codIncIRRF','62','Fundo de Aposentadoria Programada Individual FAPI 13º salário'),
(0,10,1,now(),null,'root','codIncIRRF','63','Fundação de previdência complementar do servidor público Remuneração mensal'),
(0,10,1,now(),null,'root','codIncIRRF','64','Fundação de previdência complementar do servidor público 13º salário'),
(0,10,1,now(),null,'root','codIncIRRF','65','Fundação de previdência complementar do servidor público Férias'),
(0,10,1,now(),null,'root','codIncIRRF','66','Fundo de Aposentadoria Programada Individual FAPI Férias'),
(0,10,1,now(),null,'root','codIncIRRF','67','Plano privado coletivo de assistência à saúde'),
(0,10,1,now(),null,'root','codIncIRRF','70','Parcela isenta 65 anos - Remuneração mensal'),
(0,10,1,now(),null,'root','codIncIRRF','71','Parcela isenta 65 anos - 13º salário'),
(0,10,1,now(),null,'root','codIncIRRF','72','Diárias'),
(0,10,1,now(),null,'root','codIncIRRF','73','Ajuda de custo'),
(0,10,1,now(),null,'root','codIncIRRF','74','Indenização e rescisão de contrato, inclusive a título de PDV e acidentes de trabalho'),
(0,10,1,now(),null,'root','codIncIRRF','75','Abono pecuniário'),
(0,10,1,now(),null,'root','codIncIRRF','76','Rendimento de beneficiário com moléstia grave ou acidente em serviço - Remuneração mensal'),
(0,10,1,now(),null,'root','codIncIRRF','77','Rendimento de beneficiário com moléstia grave ou acidente em serviço - 13º salário'),
(0,10,1,now(),null,'root','codIncIRRF','78','Valores pagos a titular ou sócio de microempresa ou empresa de pequeno porte, exceto pró-labore e aluguéis'),
(0,10,1,now(),null,'root','codIncIRRF','700','Auxílio moradia'),
(0,10,1,now(),null,'root','codIncIRRF','701','Parte não tributável do valor de serviço de transporte de passageiros ou cargas'),
(0,10,1,now(),null,'root','codIncIRRF','79','Outras isenções (o nome da rubrica deve ser claro para identificação da natureza dos valores)'),
(0,10,1,now(),null,'root','codIncIRRF','81','Depósito judicial'),
(0,10,1,now(),null,'root','codIncIRRF','82','Compensação judicial do ano-calendário'),
(0,10,1,now(),null,'root','codIncIRRF','83','Compensação judicial de anos anteriores'),
(0,10,1,now(),null,'root','codIncIRRF','91','Remuneração mensal'),
(0,10,1,now(),null,'root','codIncIRRF','92','13º salário'),
(0,10,1,now(),null,'root','codIncIRRF','93','Férias'),
(0,10,1,now(),null,'root','codIncIRRF','94','PLR'),
(0,10,1,now(),null,'root','codIncIRRF','95','RRA'),
(0,10,1,now(),null,'root','codIncIRRF','9011','Remuneração mensal'),
(0,10,1,now(),null,'root','codIncIRRF','9012','13º salário'),
(0,10,1,now(),null,'root','codIncIRRF','9013','Férias'),
(0,10,1,now(),null,'root','codIncIRRF','9014','PLR'),
(0,10,1,now(),null,'root','codIncIRRF','9031','Remuneração mensal'),
(0,10,1,now(),null,'root','codIncIRRF','9032','13º salário'),
(0,10,1,now(),null,'root','codIncIRRF','9033','Férias'),
(0,10,1,now(),null,'root','codIncIRRF','9034','PLR'),
(0,10,1,now(),null,'root','codIncIRRF','9831','Depósito judicial - Mensal'),
(0,10,1,now(),null,'root','codIncIRRF','9832','Depósito judicial - 13º salário'),
(0,10,1,now(),null,'root','codIncIRRF','9833','Depósito judicial - Férias'),
(0,10,1,now(),null,'root','codIncIRRF','9834','Depósito judicial - PLR'),
(0,10,1,now(),null,'root','codIncIRRF','9041','Previdência Social Oficial - PSO - Remuneração mensal'),
(0,10,1,now(),null,'root','codIncIRRF','9042','PSO - 13º salário'),
(0,10,1,now(),null,'root','codIncIRRF','9043','PSO - Férias'),
(0,10,1,now(),null,'root','codIncIRRF','9046','Previdência complementar - Salário mensal'),
(0,10,1,now(),null,'root','codIncIRRF','9047','Previdência complementar - 13º salário'),
(0,10,1,now(),null,'root','codIncIRRF','9048','Previdência complementar - Férias'),
(0,10,1,now(),null,'root','codIncIRRF','9051','Pensão alimentícia - Remuneração mensal'),
(0,10,1,now(),null,'root','codIncIRRF','9052','Pensão alimentícia - 13º salário'),
(0,10,1,now(),null,'root','codIncIRRF','9053','Pensão alimentícia - Férias'),
(0,10,1,now(),null,'root','codIncIRRF','9054','Pensão alimentícia - PLR'),
(0,10,1,now(),null,'root','codIncIRRF','9061','Fundo de Aposentadoria Programada Individual - FAPI - Remuneração mensal'),
(0,10,1,now(),null,'root','codIncIRRF','9062','Fundo de Aposentadoria Programada Individual - FAPI - 13º salário'),
(0,10,1,now(),null,'root','codIncIRRF','9063','Fundação de previdência complementar do servidor público - Remuneração mensal'),
(0,10,1,now(),null,'root','codIncIRRF','9064','Fundação de previdência complementar do servidor público - 13º salário'),
(0,10,1,now(),null,'root','codIncIRRF','9065','Fundação de previdência complementar do servidor público - Férias'),
(0,10,1,now(),null,'root','codIncIRRF','9066','Fundo de Aposentadoria Programada Individual - FAPI - Férias'),
(0,10,1,now(),null,'root','codIncIRRF','9067','Plano privado coletivo de assistência à saúde'),
(0,10,1,now(),null,'root','codIncIRRF','9082','Compensação judicial do ano-calendário'),
(0,10,1,now(),null,'root','codIncIRRF','9083','Compensação judicial de anos anteriores')