INSERT INTO `wwmgca_api`.`params` (`id`, `status`, `evento`, `created_at`, `updated_at`, `dominio`, `meta`, `value`, `label`)
values
(0,10,1,now(),null,'root','tpLograd','A','Área'),
(0,10,1,now(),null,'root','tpLograd','AC','Acesso'),
(0,10,1,now(),null,'root','tpLograd','ACA','Acampamento'),
(0,10,1,now(),null,'root','tpLograd','ACL','Acesso Local'),
(0,10,1,now(),null,'root','tpLograd','AD','Adro'),
(0,10,1,now(),null,'root','tpLograd','AE','Área Especial'),
(0,10,1,now(),null,'root','tpLograd','AER','Aeroporto'),
(0,10,1,now(),null,'root','tpLograd','AL','Alameda'),
(0,10,1,now(),null,'root','tpLograd','ALD','Aldeia'),
(0,10,1,now(),null,'root','tpLograd','AMD','Avenida Marginal Direita'),
(0,10,1,now(),null,'root','tpLograd','AME','Avenida Marginal Esquerda'),
(0,10,1,now(),null,'root','tpLograd','AN','Anel Viário'),
(0,10,1,now(),null,'root','tpLograd','ANT','Antiga Estrada'),
(0,10,1,now(),null,'root','tpLograd','ART','Artéria'),
(0,10,1,now(),null,'root','tpLograd','AT','Alto'),
(0,10,1,now(),null,'root','tpLograd','ATL','Atalho'),
(0,10,1,now(),null,'root','tpLograd','A V','Área Verde'),
(0,10,1,now(),null,'root','tpLograd','AV','Avenida'),
(0,10,1,now(),null,'root','tpLograd','AVC','Avenida Contorno'),
(0,10,1,now(),null,'root','tpLograd','AVM','Avenida Marginal'),
(0,10,1,now(),null,'root','tpLograd','AVV','Avenida Velha'),
(0,10,1,now(),null,'root','tpLograd','BAL','Balneário'),
(0,10,1,now(),null,'root','tpLograd','BC','Beco'),
(0,10,1,now(),null,'root','tpLograd','BCO','Buraco'),
(0,10,1,now(),null,'root','tpLograd','BEL','Belvedere'),
(0,10,1,now(),null,'root','tpLograd','BL','Bloco'),
(0,10,1,now(),null,'root','tpLograd','BLO','Balão'),
(0,10,1,now(),null,'root','tpLograd','BLS','Blocos'),
(0,10,1,now(),null,'root','tpLograd','BLV','Bulevar'),
(0,10,1,now(),null,'root','tpLograd','BSQ','Bosque'),
(0,10,1,now(),null,'root','tpLograd','BVD','Boulevard'),
(0,10,1,now(),null,'root','tpLograd','BX','Baixa'),
(0,10,1,now(),null,'root','tpLograd','C','Cais'),
(0,10,1,now(),null,'root','tpLograd','CAL','Calçada'),
(0,10,1,now(),null,'root','tpLograd','CAM','Caminho'),
(0,10,1,now(),null,'root','tpLograd','CAN','Canal'),
(0,10,1,now(),null,'root','tpLograd','CH','Chácara'),
(0,10,1,now(),null,'root','tpLograd','CHA','Chapadão'),
(0,10,1,now(),null,'root','tpLograd','CIC','Ciclovia'),
(0,10,1,now(),null,'root','tpLograd','CIR','Circular'),
(0,10,1,now(),null,'root','tpLograd','CJ','Conjunto'),
(0,10,1,now(),null,'root','tpLograd','CJM','Conjunto Mutirão'),
(0,10,1,now(),null,'root','tpLograd','CMP','Complexo Viário'),
(0,10,1,now(),null,'root','tpLograd','COL','Colônia'),
(0,10,1,now(),null,'root','tpLograd','COM','Comunidade'),
(0,10,1,now(),null,'root','tpLograd','CON','Condomínio'),
(0,10,1,now(),null,'root','tpLograd','COND','Condomínio'),
(0,10,1,now(),null,'root','tpLograd','COR','Corredor'),
(0,10,1,now(),null,'root','tpLograd','CPO','Campo'),
(0,10,1,now(),null,'root','tpLograd','CRG','Córrego'),
(0,10,1,now(),null,'root','tpLograd','CTN','Contorno'),
(0,10,1,now(),null,'root','tpLograd','DSC','Descida'),
(0,10,1,now(),null,'root','tpLograd','DSV','Desvio'),
(0,10,1,now(),null,'root','tpLograd','DT','Distrito'),
(0,10,1,now(),null,'root','tpLograd','EB','Entre Bloco'),
(0,10,1,now(),null,'root','tpLograd','EIM','Estrada Intermunicipal'),
(0,10,1,now(),null,'root','tpLograd','ENS','Enseada'),
(0,10,1,now(),null,'root','tpLograd','ENT','Entrada Particular'),
(0,10,1,now(),null,'root','tpLograd','EQ','Entre Quadra'),
(0,10,1,now(),null,'root','tpLograd','ESC','Escada'),
(0,10,1,now(),null,'root','tpLograd','ESD','Escadaria'),
(0,10,1,now(),null,'root','tpLograd','ESE','Estrada Estadual'),
(0,10,1,now(),null,'root','tpLograd','ESI','Estrada Vicinal'),
(0,10,1,now(),null,'root','tpLograd','ESL','Estrada de Ligação'),
(0,10,1,now(),null,'root','tpLograd','ESM','Estrada Municipal'),
(0,10,1,now(),null,'root','tpLograd','ESP','Esplanada'),
(0,10,1,now(),null,'root','tpLograd','ESS','Estrada de Servidão'),
(0,10,1,now(),null,'root','tpLograd','EST','Estrada'),
(0,10,1,now(),null,'root','tpLograd','ESV','Estrada Velha'),
(0,10,1,now(),null,'root','tpLograd','ETA','Estrada Antiga'),
(0,10,1,now(),null,'root','tpLograd','ETC','Estação'),
(0,10,1,now(),null,'root','tpLograd','ETD','Estádio'),
(0,10,1,now(),null,'root','tpLograd','ETN','Estância'),
(0,10,1,now(),null,'root','tpLograd','ETP','Estrada Particular'),
(0,10,1,now(),null,'root','tpLograd','ETT','Estacionamento'),
(0,10,1,now(),null,'root','tpLograd','EVA','Evangélica'),
(0,10,1,now(),null,'root','tpLograd','EVD','Elevada'),
(0,10,1,now(),null,'root','tpLograd','EX','Eixo Industrial'),
(0,10,1,now(),null,'root','tpLograd','FAV','Favela'),
(0,10,1,now(),null,'root','tpLograd','FAZ','Fazenda'),
(0,10,1,now(),null,'root','tpLograd','FER','Ferrovia'),
(0,10,1,now(),null,'root','tpLograd','FNT','Fonte'),
(0,10,1,now(),null,'root','tpLograd','FRA','Feira'),
(0,10,1,now(),null,'root','tpLograd','FTE','Forte'),
(0,10,1,now(),null,'root','tpLograd','GAL','Galeria'),
(0,10,1,now(),null,'root','tpLograd','GJA','Granja'),
(0,10,1,now(),null,'root','tpLograd','HAB','Núcleo Habitacional'),
(0,10,1,now(),null,'root','tpLograd','IA','Ilha'),
(0,10,1,now(),null,'root','tpLograd','IGP','Igarapé'),
(0,10,1,now(),null,'root','tpLograd','IND','Indeterminado'),
(0,10,1,now(),null,'root','tpLograd','IOA','Ilhota'),
(0,10,1,now(),null,'root','tpLograd','JD','Jardim'),
(0,10,1,now(),null,'root','tpLograd','JDE','Jardinete'),
(0,10,1,now(),null,'root','tpLograd','LD','Ladeira'),
(0,10,1,now(),null,'root','tpLograd','LGA','Lagoa'),
(0,10,1,now(),null,'root','tpLograd','LGO','Lago'),
(0,10,1,now(),null,'root','tpLograd','LOT','Loteamento'),
(0,10,1,now(),null,'root','tpLograd','LRG','Largo'),
(0,10,1,now(),null,'root','tpLograd','LT','Lote'),
(0,10,1,now(),null,'root','tpLograd','MER','Mercado'),
(0,10,1,now(),null,'root','tpLograd','MNA','Marina'),
(0,10,1,now(),null,'root','tpLograd','MOD','Modulo'),
(0,10,1,now(),null,'root','tpLograd','MRG','Projeção'),
(0,10,1,now(),null,'root','tpLograd','MRO','Morro'),
(0,10,1,now(),null,'root','tpLograd','MTE','Monte'),
(0,10,1,now(),null,'root','tpLograd','NUC','Núcleo'),
(0,10,1,now(),null,'root','tpLograd','NUR','Núcleo Rural'),
(0,10,1,now(),null,'root','tpLograd','O','Outros'),
(0,10,1,now(),null,'root','tpLograd','OUT','Outeiro'),
(0,10,1,now(),null,'root','tpLograd','PAR','Paralela'),
(0,10,1,now(),null,'root','tpLograd','PAS','Passeio'),
(0,10,1,now(),null,'root','tpLograd','PAT','Pátio'),
(0,10,1,now(),null,'root','tpLograd','PC','Praça'),
(0,10,1,now(),null,'root','tpLograd','PCE','Praça de Esportes'),
(0,10,1,now(),null,'root','tpLograd','PDA','Parada'),
(0,10,1,now(),null,'root','tpLograd','PDO','Paradouro'),
(0,10,1,now(),null,'root','tpLograd','PNT','Ponta'),
(0,10,1,now(),null,'root','tpLograd','PR','Praia'),
(0,10,1,now(),null,'root','tpLograd','PRL','Prolongamento'),
(0,10,1,now(),null,'root','tpLograd','PRM','Parque Municipal'),
(0,10,1,now(),null,'root','tpLograd','PRQ','Parque'),
(0,10,1,now(),null,'root','tpLograd','PRR','Parque Residencial'),
(0,10,1,now(),null,'root','tpLograd','PSA','Passarela'),
(0,10,1,now(),null,'root','tpLograd','PSG','Passagem'),
(0,10,1,now(),null,'root','tpLograd','PSP','Passagem de Pedestre'),
(0,10,1,now(),null,'root','tpLograd','PSS','Passagem Subterrânea'),
(0,10,1,now(),null,'root','tpLograd','PTE','Ponte'),
(0,10,1,now(),null,'root','tpLograd','PTO','Porto'),
(0,10,1,now(),null,'root','tpLograd','Q','Quadra'),
(0,10,1,now(),null,'root','tpLograd','QTA','Quinta'),
(0,10,1,now(),null,'root','tpLograd','QTS','Quintas'),
(0,10,1,now(),null,'root','tpLograd','R','Rua'),
(0,10,1,now(),null,'root','tpLograd','R I','Rua Integração'),
(0,10,1,now(),null,'root','tpLograd','R L','Rua de Ligação'),
(0,10,1,now(),null,'root','tpLograd','R P','Rua Particular'),
(0,10,1,now(),null,'root','tpLograd','R V','Rua Velha'),
(0,10,1,now(),null,'root','tpLograd','RAM','Ramal'),
(0,10,1,now(),null,'root','tpLograd','RCR','Recreio'),
(0,10,1,now(),null,'root','tpLograd','REC','Recanto'),
(0,10,1,now(),null,'root','tpLograd','RER','Retiro'),
(0,10,1,now(),null,'root','tpLograd','RES','Residencial'),
(0,10,1,now(),null,'root','tpLograd','RET','Reta'),
(0,10,1,now(),null,'root','tpLograd','RLA','Ruela'),
(0,10,1,now(),null,'root','tpLograd','RMP','Rampa'),
(0,10,1,now(),null,'root','tpLograd','ROA','Rodo Anel'),
(0,10,1,now(),null,'root','tpLograd','ROD','Rodovia'),
(0,10,1,now(),null,'root','tpLograd','ROT','Rotula'),
(0,10,1,now(),null,'root','tpLograd','RPE','Rua de Pedestre'),
(0,10,1,now(),null,'root','tpLograd','RPR','Margem'),
(0,10,1,now(),null,'root','tpLograd','RTN','Retorno'),
(0,10,1,now(),null,'root','tpLograd','RTT','Rotatória'),
(0,10,1,now(),null,'root','tpLograd','SEG','Segunda Avenida'),
(0,10,1,now(),null,'root','tpLograd','SIT','Sitio'),
(0,10,1,now(),null,'root','tpLograd','SRV','Servidão'),
(0,10,1,now(),null,'root','tpLograd','ST','Setor'),
(0,10,1,now(),null,'root','tpLograd','SUB','Subida'),
(0,10,1,now(),null,'root','tpLograd','TCH','Trincheira'),
(0,10,1,now(),null,'root','tpLograd','TER','Terminal'),
(0,10,1,now(),null,'root','tpLograd','TR','Trecho'),
(0,10,1,now(),null,'root','tpLograd','TRV','Trevo'),
(0,10,1,now(),null,'root','tpLograd','TUN','Túnel'),
(0,10,1,now(),null,'root','tpLograd','TV','Travessa'),
(0,10,1,now(),null,'root','tpLograd','TVP','Travessa Particular'),
(0,10,1,now(),null,'root','tpLograd','TVV','Travessa Velha'),
(0,10,1,now(),null,'root','tpLograd','UNI','Unidade'),
(0,10,1,now(),null,'root','tpLograd','V','Via'),
(0,10,1,now(),null,'root','tpLograd','V C','Via Coletora'),
(0,10,1,now(),null,'root','tpLograd','V L','Via Local'),
(0,10,1,now(),null,'root','tpLograd','VAC','Via de Acesso'),
(0,10,1,now(),null,'root','tpLograd','VAL','Vala'),
(0,10,1,now(),null,'root','tpLograd','VCO','Via Costeira'),
(0,10,1,now(),null,'root','tpLograd','VD','Viaduto'),
(0,10,1,now(),null,'root','tpLograd','V-E','Via Expressa'),
(0,10,1,now(),null,'root','tpLograd','VER','Vereda'),
(0,10,1,now(),null,'root','tpLograd','VEV','Via Elevado'),
(0,10,1,now(),null,'root','tpLograd','VL','Vila'),
(0,10,1,now(),null,'root','tpLograd','VLA','Viela'),
(0,10,1,now(),null,'root','tpLograd','VLE','Vale'),
(0,10,1,now(),null,'root','tpLograd','VLT','Via Litorânea'),
(0,10,1,now(),null,'root','tpLograd','VPE','Via de Pedestre'),
(0,10,1,now(),null,'root','tpLograd','VRT','Variante'),
(0,10,1,now(),null,'root','tpLograd','ZIG','Zigue-Zague')