INSERT INTO `wwmgca_app`.`params` (`id`, `status`, `evento`, `created_at`, `updated_at`, `dominio`, `meta`, `value`, `label`)
values
(0,10,1,now(),null,'root','mtvAfast','01','Acidente/doença do trabalho'),
(0,10,1,now(),null,'root','mtvAfast','03','Acidente/doença não relacionada ao trabalho'),
(0,10,1,now(),null,'root','mtvAfast','05','Afastamento/licença de servidor público prevista em estatuto, sem remuneração'),
(0,10,1,now(),null,'root','mtvAfast','06','Aposentadoria por invalidez'),
(0,10,1,now(),null,'root','mtvAfast','07','Acompanhamento - Licença para acompanhamento de membro da família enfermo'),
(0,10,1,now(),null,'root','mtvAfast','10','Afastamento/licença de servidor público prevista em estatuto, com remuneração'),
(0,10,1,now(),null,'root','mtvAfast','11','Cárcere'),
(0,10,1,now(),null,'root','mtvAfast','12','Cargo eletivo - Candidato a cargo eletivo - Art. 25, parágrafo único, da Lei 7.664/1988 - Celetistas em geral'),
(0,10,1,now(),null,'root','mtvAfast','13','Cargo eletivo - Art. 1°, inciso II, alínea "l", da Lei Compl 64/1990 - Servidor público, estatutário ou não, dos órgãos,entidades da Adm Direta ou Indireta da União,Estados,DF,Municípios e fundações do Poder Público'),
(0,10,1,now(),null,'root','mtvAfast','15','Gozo de férias ou recesso - Afastamento temporário para o gozo de férias ou recesso'),
(0,10,1,now(),null,'root','mtvAfast','16','Licença remunerada - Lei, liberalidade da empresa ou Acordo/Convenção Coletiva de Trabalho'),
(0,10,1,now(),null,'root','mtvAfast','17','Licença maternidade'),
(0,10,1,now(),null,'root','mtvAfast','18','Licença maternidade - Prorrogação por 60 dias, Lei 11.770/2008 (Empresa Cidadã), inclusive para o cônjuge sobrevivente'),
(0,10,1,now(),null,'root','mtvAfast','19','Licença maternidade - Afastamento temporário por motivo de aborto não criminoso'),
(0,10,1,now(),null,'root','mtvAfast','20','Licença maternidade - Afastamento temporário por motivo de licença-maternidade para o cônjuge sobrevivente ou decorrente de adoção ou de guarda judicial de criança'),
(0,10,1,now(),null,'root','mtvAfast','21','Licença não remunerada ou sem vencimento'),
(0,10,1,now(),null,'root','mtvAfast','22','Mandato eleitoral - Afastamento temporário para o exercício de mandato eleitoral'),
(0,10,1,now(),null,'root','mtvAfast','24','Mandato sindical - Afastamento temporário para exercício de mandato sindical'),
(0,10,1,now(),null,'root','mtvAfast','25','Mulher vítima de violência - Art. 9º, § 2º, inciso II, da Lei 11.340/2006 - Lei Maria da Penha'),
(0,10,1,now(),null,'root','mtvAfast','26','Participação de empregado no Conselho Nacional de Previdência Social - CNPS - Art. 3º da Lei 8.213/1991'),
(0,10,1,now(),null,'root','mtvAfast','27','Qualificação - Afastamento por suspensão do contrato de acordo com o art. 476-A da CLT'),
(0,10,1,now(),null,'root','mtvAfast','28','Representante sindical - Afastamento pelo tempo que se fizer necessário, quando, na qualidade de representante de entidade sindical, estiver participando de reunião oficial de organismo internacional do qual o Brasil seja membro'),
(0,10,1,now(),null,'root','mtvAfast','29','Serviço militar - Afastamento temporário para prestar serviço militar obrigatório'),
(0,10,1,now(),null,'root','mtvAfast','31','Servidor público em disponibilidade'),
(0,10,1,now(),null,'root','mtvAfast','34','Inatividade do trabalhador avulso (portuário ou não portuário) por período superior a 90 dias'),
(0,10,1,now(),null,'root','mtvAfast','35','Licença maternidade - Antecipação e/ou prorrogação mediante atestado médico'),
(0,10,1,now(),null,'root','mtvAfast','36','Afastamento temporário de exercente de mandato eletivo para cargo em comissão'),
(0,10,1,now(),null,'root','mtvAfast','38','Impedimento de concorrência à escala para trabalho avulso'),
(0,10,1,now(),null,'root','mtvAfast','39','Suspensão de pagamento de servidor público por não recadastramento'),
(0,10,1,now(),null,'root','mtvAfast','40','Exercício em outro órgão de servidor ou empregado público cedido'),
(0,10,1,now(),null,'root','mtvAfast','41','Qualificação - Afastamento por suspensão do contrato de acordo com o art. 17 da MP 1.116/2022'),
(0,10,1,now(),null,'root','mtvAfast','42','Qualificação - Afastamento por suspensão do contrato de acordo com o art. 19 da MP 1.116/2022')