INSERT INTO `wwmgca_app`.`params` (`id`, `status`, `evento`, `created_at`, `updated_at`, `dominio`, `meta`, `value`, `label`)
values
(0,10,1,now(),null,'root','codCateg','101','Empregado - Geral, inclusive o empregado público da administração direta ou indireta contratado pela CLT'),
(0,10,1,now(),null,'root','codCateg','102','Empregado - Trabalhador rural por pequeno prazo da Lei 11.718/2008'),
(0,10,1,now(),null,'root','codCateg','103','Empregado - Aprendiz'),
(0,10,1,now(),null,'root','codCateg','104','Empregado - Doméstico'),
(0,10,1,now(),null,'root','codCateg','105','Empregado - Contrato a termo firmado nos termos da Lei 9.601/1998'),
(0,10,1,now(),null,'root','codCateg','106','Trabalhador temporário - Contrato nos termos da Lei 6.019/1974'),
(0,10,1,now(),null,'root','codCateg','107','Empregado - Contrato de trabalho Verde e Amarelo - sem acordo para antecipação mensal da multa rescisória do FGTS'),
(0,10,1,now(),null,'root','codCateg','108','Empregado - Contrato de trabalho Verde e Amarelo - com acordo para antecipação mensal da multa rescisória do FGTS'),
(0,10,1,now(),null,'root','codCateg','111','Empregado - Contrato de trabalho intermitente'),
(0,10,1,now(),null,'root','codCateg','201','Trabalhador avulso portuário'),
(0,10,1,now(),null,'root','codCateg','202','Trabalhador avulso não portuário'),
(0,10,1,now(),null,'root','codCateg','301','Servidor público titular de cargo efetivo, magistrado, ministro de Tribunal de Contas, conselheiro de Tribunal de Contas e membro do Ministério Público'),
(0,10,1,now(),null,'root','codCateg','302','Servidor público ocupante de cargo exclusivo em comissão'),
(0,10,1,now(),null,'root','codCateg','303','Exercente de mandato eletivo'),
(0,10,1,now(),null,'root','codCateg','304','Servidor público exercente de mandato eletivo, inclusive com exercício de cargo em comissão'),
(0,10,1,now(),null,'root','codCateg','305','Servidor público indicado para conselho ou órgão deliberativo, na condição de representante do governo, órgão ou entidade da administração pública'),
(0,10,1,now(),null,'root','codCateg','306','Servidor público contratado por tempo determinado, sujeito a regime administrativo especial definido em lei própria'),
(0,10,1,now(),null,'root','codCateg','307','Militar'),
(0,10,1,now(),null,'root','codCateg','308','Conscrito'),
(0,10,1,now(),null,'root','codCateg','309','Agente público - Outros'),
(0,10,1,now(),null,'root','codCateg','310','Servidor público eventual'),
(0,10,1,now(),null,'root','codCateg','311','Ministros, juízes, procuradores, promotores ou oficiais de justiça à disposição da Justiça Eleitoral'),
(0,10,1,now(),null,'root','codCateg','312','Auxiliar local'),
(0,10,1,now(),null,'root','codCateg','313','Servidor público exercente de atividade de instrutoria, capacitação, treinamento, curso ou concurso, ou convocado para pareceres técnicos ou depoimentos'),
(0,10,1,now(),null,'root','codCateg','401','Dirigente sindical - Informação prestada pelo sindicato'),
(0,10,1,now(),null,'root','codCateg','410','Trabalhador cedido/exercício em outro órgão/juiz auxiliar - Informação prestada pelo cessionário/destino'),
(0,10,1,now(),null,'root','codCateg','501','Dirigente sindical - Segurado especial'),
(0,10,1,now(),null,'root','codCateg','701','Contribuinte individual - Autônomo em geral, exceto se enquadrado em uma das demais categorias de contribuinte individual'),
(0,10,1,now(),null,'root','codCateg','711','Contribuinte individual - Transportador autônomo de passageiros'),
(0,10,1,now(),null,'root','codCateg','712','Contribuinte individual - Transportador autônomo de carga'),
(0,10,1,now(),null,'root','codCateg','721','Contribuinte individual - Diretor não empregado, com FGTS'),
(0,10,1,now(),null,'root','codCateg','722','Contribuinte individual - Diretor não empregado, sem FGTS'),
(0,10,1,now(),null,'root','codCateg','723','Contribuinte individual - Empresário, sócio e membro de conselho de administração ou fiscal'),
(0,10,1,now(),null,'root','codCateg','731','Contribuinte individual - Cooperado que presta serviços por intermédio de cooperativa de trabalho'),
(0,10,1,now(),null,'root','codCateg','734','Contribuinte individual - Transportador cooperado que presta serviços por intermédio de cooperativa de trabalho'),
(0,10,1,now(),null,'root','codCateg','738','Contribuinte individual - Cooperado filiado a cooperativa de produção'),
(0,10,1,now(),null,'root','codCateg','741','Contribuinte individual - Microempreendedor individual'),
(0,10,1,now(),null,'root','codCateg','751','Contribuinte individual - Magistrado classista temporário da Justiça do Trabalho ou da Justiça Eleitoral que seja aposentado de qualquer regime previdenciário'),
(0,10,1,now(),null,'root','codCateg','761','Contribuinte individual - Associado eleito para direção de cooperativa, associação ou entidade de classe, bem como síndico ou administrador eleito para exercer atividade de direção condominial, desde que recebam remuneração'),
(0,10,1,now(),null,'root','codCateg','771','Contribuinte individual - Membro de conselho tutelar, nos termos da Lei 8.069/1990'),
(0,10,1,now(),null,'root','codCateg','781','Ministro de confissão religiosa ou membro de vida consagrada, de congregação ou de ordem religiosa'),
(0,10,1,now(),null,'root','codCateg','901','Estagiário'),
(0,10,1,now(),null,'root','codCateg','902','Médico residente ou residente em área profissional de saúde'),
(0,10,1,now(),null,'root','codCateg','903','Bolsista'),
(0,10,1,now(),null,'root','codCateg','904','Participante de curso de formação, como etapa de concurso público, sem vínculo de emprego/estatutário'),
(0,10,1,now(),null,'root','codCateg','906','Beneficiário do Programa Nacional de Prestação de Serviço Civil Voluntário')